export const SIGNUP_DATA_REQUEST = 'SIGNUP_DATA_REQUEST';
export const SIGNUP_DATA_SUCCESS = 'SIGNUP_DATA_SUCCESS';
export const SIGNUP_DATA_FAILURE = 'SIGNUP_DATA_FAILURE';
export const SIGNIN_DATA_REQUEST = 'SIGNIN_DATA_REQUEST';
export const SIGNIN_DATA_SUCCESS = 'SIGNIN_DATA_SUCCESS';
export const SIGNIN_DATA_FAILURE = 'SIGNIN_DATA_FAILURE';